-- =============================================================================
-- Seed du menu Kaytôri — GÉNÉRÉ par `npm run supabase:seed` depuis src/data/yumloMenu.ts.
-- Ne pas éditer à la main.
--
-- 31 catégories, 214 produits, 67 variantes.
-- Idempotent : relançable sans doublon (upsert par clé primaire, aucune suppression).
-- Attention : un nouveau passage remet les lignes concernées à l'état du fichier statique.
-- =============================================================================

begin;

insert into public.categories (id, name, sort_order, is_active, display_mode) values
  ('starters', 'Starters', 0, true, 'list'),
  ('nems-gyoza-rouleaux-de-printemps', 'Nems & Gyoza & Rouleaux de printemps', 1, true, 'list'),
  ('sushi-fusion', 'Sushi Fusion', 2, true, 'list'),
  ('yakitori', 'Yakitori', 3, true, 'list'),
  ('soupes', 'Soupes', 4, true, 'list'),
  ('salades', 'Salades', 5, true, 'list'),
  ('poke-bowl', 'Poké Bowl', 6, true, 'list'),
  ('tartare', 'Tartare', 7, true, 'list'),
  ('chirashi', 'Chirashi', 8, true, 'list'),
  ('sashimi', 'Sashimi', 9, true, 'list'),
  ('carpaccio', 'Carpaccio', 10, true, 'list'),
  ('tacos', 'Tacos', 11, true, 'list'),
  ('crispy-rice', 'Crispy Rice', 12, true, 'list'),
  ('nigiri', 'Nigiri', 13, true, 'list'),
  ('maki', 'Maki', 14, true, 'list'),
  ('futomaki', 'Futomaki', 15, true, 'list'),
  ('california-roll', 'California Roll', 16, true, 'list'),
  ('special-roll', 'Special Roll', 17, true, 'list'),
  ('aromaki', 'Aromaki', 18, true, 'list'),
  ('blossom', 'Blossom', 19, true, 'list'),
  ('premium', 'Premium', 20, true, 'list'),
  ('makito-fry', 'Makito Fry', 21, true, 'list'),
  ('crispy-roll', 'Crispy Roll', 22, true, 'list'),
  ('crunchy-roll', 'Crunchy Roll', 23, true, 'list'),
  ('wok-thai', 'Wok & Thaï', 24, true, 'list'),
  ('bentos', 'Bentos', 25, true, 'list'),
  ('plats-thai', 'Plats Thaï', 26, true, 'plats_thai_sorted'),
  ('assortiments', 'Assortiments', 27, true, 'assortiments_by_pcs'),
  ('desserts', 'Desserts', 28, true, 'list'),
  ('jus', 'Jus', 29, true, 'list'),
  ('boissons', 'Boissons', 30, true, 'list')
on conflict (id) do update set
  name = excluded.name,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  display_mode = excluded.display_mode;

insert into public.products (id, category_id, name, description, price, currency, image_url, thumb_small_url, thumb_large_url, sort_order, is_active) values
  ('f9047d3930', 'bentos', 'Bento A', 'Salade veggie, 2 nems poulet, 4 ébi fry, wok poulet', '105.00', 'MAD', '/menu-hd-onglet36/bento-a.jpg', '/menu-thumbs/menu-hd-onglet36/bento-a-224.webp', '/menu-thumbs/menu-hd-onglet36/bento-a-336.webp', 0, true),
  ('bd099ce53c', 'bentos', 'Bento B', '6 Aromaki saumon, salade viet, 4 ébi fry, 4 croquettes saumon.', '129.00', 'MAD', '/menu-hd-onglet36/bento-b.jpg', '/menu-thumbs/menu-hd-onglet36/bento-b-224.webp', '/menu-thumbs/menu-hd-onglet36/bento-b-336.webp', 1, true),
  ('d4738254f1', 'bentos', 'Bento C', '1 Nem poulet, 1 gambas panée, salade gambas, 4 eby fry, 4 california eby, 4 california classic', '124.00', 'MAD', '/menu-hd-onglet36/bento-c.jpg', '/menu-thumbs/menu-hd-onglet36/bento-c-224.webp', '/menu-thumbs/menu-hd-onglet36/bento-c-336.webp', 2, true),
  ('66073a8aee', 'bentos', 'Bento D', '4 Fry Ebi Fry, 4 Shake Yaki, salade gambas, yakitori Bœuf fromage.', '135.00', 'MAD', '/menu-hd-onglet36/bento-d.jpg', '/menu-thumbs/menu-hd-onglet36/bento-d-224.webp', '/menu-thumbs/menu-hd-onglet36/bento-d-336.webp', 3, true),
  ('cba8d279df', 'bentos', 'Bento E', 'Salade viet, fry eby fry, wok végétarien, brochettes bœuf fromage', '119.00', 'MAD', '/menu-hd-onglet36/bento-e.jpg', '/menu-thumbs/menu-hd-onglet36/bento-e-224.webp', '/menu-thumbs/menu-hd-onglet36/bento-e-336.webp', 4, true),
  ('6a0c00190c', 'bentos', 'Bento F', '4 Croquette saumon, 4 ébi fry, 2 bœuf fromage, 1 ébi tempura, 1 nems poulet.', '129.00', 'MAD', '/menu-hd-onglet36/bento-f.jpg', '/menu-thumbs/menu-hd-onglet36/bento-f-224.webp', '/menu-thumbs/menu-hd-onglet36/bento-f-336.webp', 5, true),
  ('d2ba4b91b8', 'bentos', 'Bento G', '1 Nem poulet, 1 gambas pané, salade viet, 4 fry eby fry, riz cantonais crevettes.', '128.00', 'MAD', '/menu-hd-onglet36/bento-g.jpg', '/menu-thumbs/menu-hd-onglet36/bento-g-224.webp', '/menu-thumbs/menu-hd-onglet36/bento-g-336.webp', 6, true),
  ('d570740bae', 'bentos', 'Bento H', 'Salade veggie, 4 gambas dynamite, 4 California eby fry, wok poulet.', '128.00', 'MAD', '/menu-hd-onglet36/bento-h.jpg', '/menu-thumbs/menu-hd-onglet36/bento-h-224.webp', '/menu-thumbs/menu-hd-onglet36/bento-h-336.webp', 7, true),
  ('b6fe11da37', 'starters', 'Saumon Wakamé Avocat', 'Saumon', '48.00', 'MAD', '/starters-hd/saumon-wakame-avocat.png', '/menu-thumbs/starters-hd/saumon-wakame-avocat-224.webp', '/menu-thumbs/starters-hd/saumon-wakame-avocat-336.webp', 8, true),
  ('2a41bacc9f', 'starters', 'Crevettes Tempura 5 pcs', 'Crevettes', '45.00', 'MAD', '/starters-hd/crevettes-tempura.png', '/menu-thumbs/starters-hd/crevettes-tempura-224.webp', '/menu-thumbs/starters-hd/crevettes-tempura-336.webp', 9, true),
  ('4bb9d46122', 'starters', 'Crevettes Dynamite', 'Crevettes', '49.00', 'MAD', '/starters-hd/crevettes-dynamite.png', '/menu-thumbs/starters-hd/crevettes-dynamite-224.webp', '/menu-thumbs/starters-hd/crevettes-dynamite-336.webp', 10, true),
  ('3f0f832948', 'starters', 'Saumon Sweet & Sour', 'Saumon', '49.00', 'MAD', '/starters-hd/saumon-sweet-sour.png', '/menu-thumbs/starters-hd/saumon-sweet-sour-224.webp', '/menu-thumbs/starters-hd/saumon-sweet-sour-336.webp', 11, true),
  ('c4b4c870b0', 'starters', 'Poulet Sweet & Sour', 'Poulet', '44.00', 'MAD', '/starters-hd/poulet-sweet-sour.png', '/menu-thumbs/starters-hd/poulet-sweet-sour-224.webp', '/menu-thumbs/starters-hd/poulet-sweet-sour-336.webp', 12, true),
  ('8f3c2a91b0', 'starters', 'Croquettes (5 pcs)', 'Au choix : fromage, poulet ou saumon — sauce maison.', '39.00', 'MAD', '/starters-hd/croquettes.png', '/menu-thumbs/starters-hd/croquettes-224.webp', '/menu-thumbs/starters-hd/croquettes-336.webp', 13, true),
  ('2501bc64fe', 'starters', 'Poulet Karaage', 'Poulet', '39.00', 'MAD', '/starters-hd/poulet-karaage.jpg', '/menu-thumbs/starters-hd/poulet-karaage-224.webp', '/menu-thumbs/starters-hd/poulet-karaage-336.webp', 14, true),
  ('c1d464c327', 'starters', 'Salade de Choux', '', '24.00', 'MAD', '/starters-hd/salade-de-choux.jpg', '/menu-thumbs/starters-hd/salade-de-choux-224.webp', '/menu-thumbs/starters-hd/salade-de-choux-336.webp', 15, true),
  ('dfa255110e', 'starters', 'Edamame Spicy', '', '39.00', 'MAD', '/starters-hd/edamame-spicy.jpg', '/menu-thumbs/starters-hd/edamame-spicy-224.webp', '/menu-thumbs/starters-hd/edamame-spicy-336.webp', 16, true),
  ('f7dbe92aae', 'starters', 'Edamame', '', '39.00', 'MAD', '/starters-hd/edamame.jpg', '/menu-thumbs/starters-hd/edamame-224.webp', '/menu-thumbs/starters-hd/edamame-336.webp', 17, true),
  ('140ae41112', 'starters', 'Goma Wakamé', '', '39.00', 'MAD', '/starters-hd/goma-wakame.jpg', '/menu-thumbs/starters-hd/goma-wakame-224.webp', '/menu-thumbs/starters-hd/goma-wakame-336.webp', 18, true),
  ('4d8b7659dc', 'starters', 'Riz Vinaigré', '', '20.00', 'MAD', '/starters-hd/riz-vinaigre.jpg', '/menu-thumbs/starters-hd/riz-vinaigre-224.webp', '/menu-thumbs/starters-hd/riz-vinaigre-336.webp', 19, true),
  ('228ccfc51d', 'starters', 'Riz Nature', '', '15.00', 'MAD', '/starters-hd/riz-nature.jpg', '/menu-thumbs/starters-hd/riz-nature-224.webp', '/menu-thumbs/starters-hd/riz-nature-336.webp', 20, true),
  ('a1aee64eaf', 'nems-gyoza-rouleaux-de-printemps', 'Gyoza', '4 Pièces — au choix.', '44.00', 'MAD', '/menu-hd-onglet2/gyoza.png', '/menu-thumbs/menu-hd-onglet2/gyoza-224.webp', '/menu-thumbs/menu-hd-onglet2/gyoza-336.webp', 21, true),
  ('a720b7b300', 'nems-gyoza-rouleaux-de-printemps', 'Nems', '4 pièces — au choix.', '39.00', 'MAD', '/menu-hd-onglet2/nems.png', '/menu-thumbs/menu-hd-onglet2/nems-224.webp', '/menu-thumbs/menu-hd-onglet2/nems-336.webp', 22, true),
  ('1842edff6e', 'sushi-fusion', 'Sushi Gratiné', 'Gratiné au choix — sauce maison.', '78.00', 'MAD', '/menu-hd-onglet3/sushi-gratine.jpg', '/menu-thumbs/menu-hd-onglet3/sushi-gratine-224.webp', '/menu-thumbs/menu-hd-onglet3/sushi-gratine-336.webp', 23, true),
  ('da6c1fe793', 'sushi-fusion', 'Pizza Saumon Crabe', 'Saumon, surimi, crabe, avocat, mozzarelle, tobiko 8 Pièces', '59.00', 'MAD', '/menu-hd-onglet3/pizza-saumon-crabe.jpg', '/menu-thumbs/menu-hd-onglet3/pizza-saumon-crabe-224.webp', '/menu-thumbs/menu-hd-onglet3/pizza-saumon-crabe-336.webp', 24, true),
  ('f6cb920bcd', 'sushi-fusion', 'Pizza Tropicale', 'Crevettes, mangue, surimi, mozzarelle, tobiko 8 Pièces', '54.00', 'MAD', '/menu-hd-onglet3/pizza-tropicale.jpg', '/menu-thumbs/menu-hd-onglet3/pizza-tropicale-224.webp', '/menu-thumbs/menu-hd-onglet3/pizza-tropicale-336.webp', 25, true),
  ('0ba6c99141', 'sushi-fusion', 'Pizza Saumon Mozza', 'Saumon, surimi, mozzarelle, tobiko 8 Pièces', '54.00', 'MAD', '/menu-hd-onglet3/pizza-saumon-mozza.jpg', '/menu-thumbs/menu-hd-onglet3/pizza-saumon-mozza-224.webp', '/menu-thumbs/menu-hd-onglet3/pizza-saumon-mozza-336.webp', 26, true),
  ('79bda10a6e', 'sushi-fusion', 'Sushi Burger', 'Riz croustillant, cheese, surimi épicé, goma wakamé, tobiko, sauce japonaise.', '59.00', 'MAD', '/menu-hd-onglet3/burger.jpg', '/menu-thumbs/menu-hd-onglet3/burger-224.webp', '/menu-thumbs/menu-hd-onglet3/burger-336.webp', 27, true),
  ('b6220c2315', 'sushi-fusion', 'Crunchy Burrito', 'Avocat, surimi épicé, goma wakamé, tobiko, sauce japonaise, cheese, riz croustillant', '84.15', 'MAD', '/menu-hd-onglet3/crunchy-burrito.jpg', '/menu-thumbs/menu-hd-onglet3/crunchy-burrito-224.webp', '/menu-thumbs/menu-hd-onglet3/crunchy-burrito-336.webp', 28, true),
  ('5a7a6c1ff9', 'sushi-fusion', 'Sushi Burrito', 'Riz, cheese, surimi épicé, goma wakamé, tobiko, sauce japonaise.', '59.00', 'MAD', '/menu-hd-onglet3/sushi-burrito.jpg', '/menu-thumbs/menu-hd-onglet3/sushi-burrito-224.webp', '/menu-thumbs/menu-hd-onglet3/sushi-burrito-336.webp', 29, true),
  ('76d7875ff7', 'nems-gyoza-rouleaux-de-printemps', 'Rouleaux de Printemps (8 pcs)', 'Au choix : végétarien, poulet ou crevettes — 8 pièces, sauce au choix.', '39.00', 'MAD', '/menu-hd-onglet2/rouleau-de-printemps.jpg', '/menu-thumbs/menu-hd-onglet2/rouleau-de-printemps-224.webp', '/menu-thumbs/menu-hd-onglet2/rouleau-de-printemps-336.webp', 30, true),
  ('da996bc4a5', 'nems-gyoza-rouleaux-de-printemps', 'Bouchées Vapeur', '4 Pièces — au choix.', '44.00', 'MAD', '/menu-hd-onglet2/bouchees-vapeur.jpg', '/menu-thumbs/menu-hd-onglet2/bouchees-vapeur-224.webp', '/menu-thumbs/menu-hd-onglet2/bouchees-vapeur-336.webp', 31, true),
  ('a043965b0e', 'yakitori', 'Boeuf Fromage Pané 2 pcs', 'Servi avec du riz', '54.00', 'MAD', '/menu-hd-onglet4/yakitori-boeuf-fromage-pane.png', '/menu-thumbs/menu-hd-onglet4/yakitori-boeuf-fromage-pane-224.webp', '/menu-thumbs/menu-hd-onglet4/yakitori-boeuf-fromage-pane-336.webp', 32, true),
  ('99671b537e', 'yakitori', 'Yakitori Bœuf Fromage 2 pcs', 'Servi avec du riz', '49.00', 'MAD', '/menu-hd-onglet4/yakitori-boeuf-fromage.png', '/menu-thumbs/menu-hd-onglet4/yakitori-boeuf-fromage-224.webp', '/menu-thumbs/menu-hd-onglet4/yakitori-boeuf-fromage-336.webp', 33, true),
  ('1dfecb937d', 'yakitori', 'Yakitori Poulet Pané 2 pcs', 'Servi avec du riz', '44.00', 'MAD', '/menu-hd-onglet4/yakitori-poulet-pane.png', '/menu-thumbs/menu-hd-onglet4/yakitori-poulet-pane-224.webp', '/menu-thumbs/menu-hd-onglet4/yakitori-poulet-pane-336.webp', 34, true),
  ('7cb2b13500', 'yakitori', 'Yakitori Poulet Tsukun 2 pcs', 'Servi avec du riz', '39.00', 'MAD', '/menu-hd-onglet4/yakitori-poulet-tsukun.png', '/menu-thumbs/menu-hd-onglet4/yakitori-poulet-tsukun-224.webp', '/menu-thumbs/menu-hd-onglet4/yakitori-poulet-tsukun-336.webp', 35, true),
  ('261985956b', 'soupes', 'Soupe Tom Kha Kaï', 'Poulet, lait de coco, tomate cerise, citronnelle, champignon', '54.00', 'MAD', '/menu-hd-onglet5/soupe-tom-kha-kai.png', '/menu-thumbs/menu-hd-onglet5/soupe-tom-kha-kai-224.webp', '/menu-thumbs/menu-hd-onglet5/soupe-tom-kha-kai-336.webp', 36, true),
  ('fb33c65f0c', 'soupes', 'Soupe Royale', 'Crevettes, calamar, saumon, boulettes de poulet, surimi, champignon noir, vermicelle, ciboulette', '54.00', 'MAD', '/menu-hd-onglet5/soupe-royale.png', '/menu-thumbs/menu-hd-onglet5/soupe-royale-224.webp', '/menu-thumbs/menu-hd-onglet5/soupe-royale-336.webp', 37, true),
  ('a03e0a6aff', 'soupes', 'Soupe Tom Yum', 'Crevettes, pate tom yum, champignon, citronnelle', '54.00', 'MAD', '/menu-hd-onglet5/soupe-tom-yum.png', '/menu-thumbs/menu-hd-onglet5/soupe-tom-yum-224.webp', '/menu-thumbs/menu-hd-onglet5/soupe-tom-yum-336.webp', 38, true),
  ('1714470567', 'soupes', 'Soupe Fruits de Mer', 'Crevettes, calamar, saumon, boulettes de poulet, surimi, champignon noir, vermicelle, ciboulette', '54.00', 'MAD', '/menu-hd-onglet5/soupe-fruits-de-mer.png', '/menu-thumbs/menu-hd-onglet5/soupe-fruits-de-mer-224.webp', '/menu-thumbs/menu-hd-onglet5/soupe-fruits-de-mer-336.webp', 39, true),
  ('58ab2c54d0', 'soupes', 'Soupe Pékinoise', 'Crevettes, poulet, vermicelle, champignon noir', '49.00', 'MAD', '/menu-hd-onglet5/soupe-pekinoise.png', '/menu-thumbs/menu-hd-onglet5/soupe-pekinoise-224.webp', '/menu-thumbs/menu-hd-onglet5/soupe-pekinoise-336.webp', 40, true),
  ('4240ad621c', 'salades', 'Salade Royale', 'Crabe, crevettes, poulet, mangue, avocat, maïs, tomate cerise, laitue', '64.00', 'MAD', '/menu-hd-onglet6/salade-royale.png', '/menu-thumbs/menu-hd-onglet6/salade-royale-224.webp', '/menu-thumbs/menu-hd-onglet6/salade-royale-336.webp', 41, true),
  ('2c80cdd361', 'salades', 'Salade Fruits de Mer', 'Calamar, crevettes, crabe, surimi, mangue, choux, carottes, laitue', '54.00', 'MAD', '/menu-hd-onglet6/salade-fruits-de-mer.jpg', '/menu-thumbs/menu-hd-onglet6/salade-fruits-de-mer-224.webp', '/menu-thumbs/menu-hd-onglet6/salade-fruits-de-mer-336.webp', 42, true),
  ('c2651f806f', 'salades', 'Salade Tropicale', 'Crevettes, avocat, surimi, pomme, concombre, maïs, tomates cerise, gouda pané', '59.00', 'MAD', '/menu-hd-onglet6/salade-tropicale.png', '/menu-thumbs/menu-hd-onglet6/salade-tropicale-224.webp', '/menu-thumbs/menu-hd-onglet6/salade-tropicale-336.webp', 43, true),
  ('b446a7355a', 'salades', 'Salade Exotic Chicken', 'Poulet pané, avocat, mangue, surimi, épis de maïs, tomate cerise, choux, carottes, tobiko', '54.00', 'MAD', '/menu-hd-onglet6/salade-exotic-chicken.png', '/menu-thumbs/menu-hd-onglet6/salade-exotic-chicken-224.webp', '/menu-thumbs/menu-hd-onglet6/salade-exotic-chicken-336.webp', 44, true),
  ('fb89c84798', 'salades', 'Salade Vietnamienne', 'Poulet, crevettes, choux, carottes, cacahuète, germe de soja, concombre, laitue, sauce viet', '54.00', 'MAD', '/menu-hd-onglet6/salade-vietnamienne.jpg', '/menu-thumbs/menu-hd-onglet6/salade-vietnamienne-224.webp', '/menu-thumbs/menu-hd-onglet6/salade-vietnamienne-336.webp', 45, true),
  ('b56ed1406f', 'salades', 'Crevettes Tempura', 'Crevettes tempura, mangue, épis de maïs, wakamé, pomme, tomate cerise, tobiko, ciboulette', '59.00', 'MAD', '/menu-hd-onglet6/salade-crevettes-tempura.jpg', '/menu-thumbs/menu-hd-onglet6/salade-crevettes-tempura-224.webp', '/menu-thumbs/menu-hd-onglet6/salade-crevettes-tempura-336.webp', 46, true),
  ('3a75439af2', 'salades', 'Exotic Del Mar', 'Saumon, crevettes, surimi, mangue, tomate cerise, choux, carottes', '64.00', 'MAD', '/menu-hd-onglet6/exotic-del-mar.jpg', '/menu-thumbs/menu-hd-onglet6/exotic-del-mar-224.webp', '/menu-thumbs/menu-hd-onglet6/exotic-del-mar-336.webp', 47, true),
  ('aa7a7bfe5c', 'salades', 'Bobun', 'Bœuf caramélisé, crevettes, nems poulet, vermicelle, légumes, cacahuètes', '69.00', 'MAD', '/menu-hd-onglet6/bobun.jpg', '/menu-thumbs/menu-hd-onglet6/bobun-224.webp', '/menu-thumbs/menu-hd-onglet6/bobun-336.webp', 48, true),
  ('743455af94', 'poke-bowl', 'Poké Saumon', 'Saumon, mangue, avocat, goma wakamé, carottes, tomate cerise, edamame, riz vinaigré', '69.00', 'MAD', '/menu-hd-onglet7-12/poke-saumon.png', '/menu-thumbs/menu-hd-onglet7-12/poke-saumon-224.webp', '/menu-thumbs/menu-hd-onglet7-12/poke-saumon-336.webp', 49, true),
  ('bd77948103', 'poke-bowl', 'Poké Crevettes', 'Crevettes, mangue, avocat, goma wakamé, carottes, tomate cerise, edamame, riz vinaigré', '65.00', 'MAD', '/menu-hd-onglet7-12/poke-crevettes.png', '/menu-thumbs/menu-hd-onglet7-12/poke-crevettes-224.webp', '/menu-thumbs/menu-hd-onglet7-12/poke-crevettes-336.webp', 50, true),
  ('5034601de3', 'poke-bowl', 'Poké Poulet', 'Poulet, mangue, avocat, goma wakamé, carottes, tomate cerise, edamame, riz vinaigré', '59.00', 'MAD', '/menu-hd-onglet7-12/poke-poulet.png', '/menu-thumbs/menu-hd-onglet7-12/poke-poulet-224.webp', '/menu-thumbs/menu-hd-onglet7-12/poke-poulet-336.webp', 51, true),
  ('d4d9f53292', 'tartare', 'Tartare Tropical', 'Saumon, mangue, avocat, tobiko, ciboulette', '59.00', 'MAD', '/menu-hd-onglet7-12/tartare-tropical.png', '/menu-thumbs/menu-hd-onglet7-12/tartare-tropical-224.webp', '/menu-thumbs/menu-hd-onglet7-12/tartare-tropical-336.webp', 52, true),
  ('1eef119afb', 'tartare', 'Tartare Saumon Avocat', 'Saumon, avocat, tobiko, kunafa, ciboulette', '59.00', 'MAD', '/menu-hd-onglet7-12/tartare-saumon-avocat.png', '/menu-thumbs/menu-hd-onglet7-12/tartare-saumon-avocat-224.webp', '/menu-thumbs/menu-hd-onglet7-12/tartare-saumon-avocat-336.webp', 53, true),
  ('a2118c7dd7', 'chirashi', 'Chirashi Saumon Avocat', 'Saumon, avocat', '64.00', 'MAD', '/menu-hd-onglet7-12/chirashi-saumon-avocat.png', '/menu-thumbs/menu-hd-onglet7-12/chirashi-saumon-avocat-224.webp', '/menu-thumbs/menu-hd-onglet7-12/chirashi-saumon-avocat-336.webp', 54, true),
  ('dbca86e5a4', 'sashimi', 'Sashimi Saumon 4 pcs', 'Saumon', '34.00', 'MAD', '/menu-hd-onglet7-12/sashimi-saumon.png', '/menu-thumbs/menu-hd-onglet7-12/sashimi-saumon-224.webp', '/menu-thumbs/menu-hd-onglet7-12/sashimi-saumon-336.webp', 55, true),
  ('5206f52f84', 'carpaccio', 'Carpaccio Saumon 8 pcs', 'Saumon', '64.00', 'MAD', '/menu-hd-onglet7-12/carpaccio-saumon.png', '/menu-thumbs/menu-hd-onglet7-12/carpaccio-saumon-224.webp', '/menu-thumbs/menu-hd-onglet7-12/carpaccio-saumon-336.webp', 56, true),
  ('2505b93cd8', 'tacos', 'Tacos Saumon Avocat 2 pcs', 'Saumon, avocat, tobiko', '39.00', 'MAD', '/menu-hd-onglet7-12/tacos-saumon-avocat.png', '/menu-thumbs/menu-hd-onglet7-12/tacos-saumon-avocat-224.webp', '/menu-thumbs/menu-hd-onglet7-12/tacos-saumon-avocat-336.webp', 57, true),
  ('8101c52f8c', 'tacos', 'Tacos Saumon Epicé 2 pcs', 'Saumon épicé, poireaux, guacamole, sésame', '39.00', 'MAD', '/menu-hd-onglet7-12/tacos-saumon-epice.png', '/menu-thumbs/menu-hd-onglet7-12/tacos-saumon-epice-224.webp', '/menu-thumbs/menu-hd-onglet7-12/tacos-saumon-epice-336.webp', 58, true),
  ('b5131a7c46', 'tacos', 'Tacos Gambas Shitaké 2 pcs', 'Gambas, champignon shitaké, sauce chili', '39.00', 'MAD', '/menu-hd-onglet7-12/tacos-gambas-shitake.png', '/menu-thumbs/menu-hd-onglet7-12/tacos-gambas-shitake-224.webp', '/menu-thumbs/menu-hd-onglet7-12/tacos-gambas-shitake-336.webp', 59, true),
  ('0d86283322', 'tacos', 'Tacos Chicken Garlic 2 pcs', 'Chicken, sauce chili', '34.00', 'MAD', '/menu-hd-onglet7-12/tacos-chicken-garlic.png', '/menu-thumbs/menu-hd-onglet7-12/tacos-chicken-garlic-224.webp', '/menu-thumbs/menu-hd-onglet7-12/tacos-chicken-garlic-336.webp', 60, true),
  ('f1773a150f', 'crispy-rice', 'Crispy Rice Saumon Avocat 2 pcs', 'Saumon, avocat', '34.00', 'MAD', '/menu-hd-onglet13/crispy-rice-saumon-avocat.png', '/menu-thumbs/menu-hd-onglet13/crispy-rice-saumon-avocat-224.webp', '/menu-thumbs/menu-hd-onglet13/crispy-rice-saumon-avocat-336.webp', 61, true),
  ('e624eac353', 'crispy-rice', 'Crispy Rice Ebi Avocat 2 pcs', 'Crevettes, avocat', '34.00', 'MAD', '/menu-hd-onglet13/crispy-rice-ebi-avocat.png', '/menu-thumbs/menu-hd-onglet13/crispy-rice-ebi-avocat-224.webp', '/menu-thumbs/menu-hd-onglet13/crispy-rice-ebi-avocat-336.webp', 62, true),
  ('b276b0ceb2', 'crispy-rice', 'Crispy Rice Mangue Avocat 2 pcs', 'Mangue, avocat', '29.00', 'MAD', '/menu-hd-onglet13/crispy-rice-mangue-avocat.png', '/menu-thumbs/menu-hd-onglet13/crispy-rice-mangue-avocat-224.webp', '/menu-thumbs/menu-hd-onglet13/crispy-rice-mangue-avocat-336.webp', 63, true),
  ('d56e6ad4c1', 'crispy-rice', 'Crispy Rice Crunchy Poulet 2 pcs', 'Poulet', '33.15', 'MAD', '/menu-hd-onglet13/crispy-rice-crunchy-poulet.png', '/menu-thumbs/menu-hd-onglet13/crispy-rice-crunchy-poulet-224.webp', '/menu-thumbs/menu-hd-onglet13/crispy-rice-crunchy-poulet-336.webp', 64, true),
  ('4cac8d8b4e', 'nigiri', 'Nigiri Saumon Avocat 2 pcs', 'Saumon, avocat', '39.00', 'MAD', '/menu-hd-onglet14/nigiri-saumon-avocat.png', '/menu-thumbs/menu-hd-onglet14/nigiri-saumon-avocat-224.webp', '/menu-thumbs/menu-hd-onglet14/nigiri-saumon-avocat-336.webp', 65, true),
  ('0055351351', 'nigiri', 'Nigiri Saumon 2 pcs', 'Saumon', '34.00', 'MAD', '/menu-hd-onglet14/nigiri-saumon.jpg', '/menu-thumbs/menu-hd-onglet14/nigiri-saumon-224.webp', '/menu-thumbs/menu-hd-onglet14/nigiri-saumon-336.webp', 66, true),
  ('9467aea043', 'nigiri', 'Nigiri Saumon Braisé 2 pcs', 'Saumon', '34.00', 'MAD', '/menu-hd-onglet14/nigiri-saumon-braise.png', '/menu-thumbs/menu-hd-onglet14/nigiri-saumon-braise-224.webp', '/menu-thumbs/menu-hd-onglet14/nigiri-saumon-braise-336.webp', 67, true),
  ('a134dbcb8f', 'maki', 'Maki Saumon Cheese', '6 Pièces', '34.00', 'MAD', '/menu-hd-onglet15/maki-saumon-cheese.png', '/menu-thumbs/menu-hd-onglet15/maki-saumon-cheese-224.webp', '/menu-thumbs/menu-hd-onglet15/maki-saumon-cheese-336.webp', 68, true),
  ('07f5e99819', 'maki', 'Maki Saumon Avocat', '6 Pièces', '34.00', 'MAD', '/menu-hd-onglet15/maki-saumon-avocat.png', '/menu-thumbs/menu-hd-onglet15/maki-saumon-avocat-224.webp', '/menu-thumbs/menu-hd-onglet15/maki-saumon-avocat-336.webp', 69, true),
  ('2594bcb7b0', 'maki', 'Maki Eby Fry', '6 Pièces', '29.00', 'MAD', '/menu-hd-onglet15/maki-eby-fry.png', '/menu-thumbs/menu-hd-onglet15/maki-eby-fry-224.webp', '/menu-thumbs/menu-hd-onglet15/maki-eby-fry-336.webp', 70, true),
  ('6be7c32896', 'maki', 'Maki Saumon', '6 Pièces', '29.00', 'MAD', '/menu-hd-onglet15/maki-saumon.png', '/menu-thumbs/menu-hd-onglet15/maki-saumon-224.webp', '/menu-thumbs/menu-hd-onglet15/maki-saumon-336.webp', 71, true),
  ('78b88fbc91', 'maki', 'Maki Avocat Cheese', '6 Pièces', '26.00', 'MAD', '/menu-hd-onglet15/maki-avocat-cheese.png', '/menu-thumbs/menu-hd-onglet15/maki-avocat-cheese-224.webp', '/menu-thumbs/menu-hd-onglet15/maki-avocat-cheese-336.webp', 72, true),
  ('48d9b28c3c', 'futomaki', 'Futomaki Crabe Mango', 'Crevettes poché, mangue, saumon, crabe, tobiko, cheese 5 Pièces', '58.00', 'MAD', '/menu-hd-onglet16/futomaki-crabe-mango.png', '/menu-thumbs/menu-hd-onglet16/futomaki-crabe-mango-224.webp', '/menu-thumbs/menu-hd-onglet16/futomaki-crabe-mango-336.webp', 73, true),
  ('f5de1461f2', 'futomaki', 'Futomaki Salmon Eby', 'Saumon, avocat, crevette pané, surimi, tobiko, cheese 5 Pièces', '49.00', 'MAD', '/menu-hd-onglet16/futomaki-salmon-eby.png', '/menu-thumbs/menu-hd-onglet16/futomaki-salmon-eby-224.webp', '/menu-thumbs/menu-hd-onglet16/futomaki-salmon-eby-336.webp', 74, true),
  ('a1051484c6', 'futomaki', 'Futomaki Eby Mango', 'Crevette pané, avocat, mangue, concombre ciselé, carottes, tobiko, cheese 5 Pièces', '49.00', 'MAD', '/menu-hd-onglet16/futomaki-eby-mango.png', '/menu-thumbs/menu-hd-onglet16/futomaki-eby-mango-224.webp', '/menu-thumbs/menu-hd-onglet16/futomaki-eby-mango-336.webp', 75, true),
  ('5f48df3cac', 'futomaki', 'Futomaki Eby Roll', 'Crevette pochée, surimi, ebi tempura, avocat, cheese 5 Pièces', '49.00', 'MAD', '/menu-hd-onglet16/futomaki-eby-roll.png', '/menu-thumbs/menu-hd-onglet16/futomaki-eby-roll-224.webp', '/menu-thumbs/menu-hd-onglet16/futomaki-eby-roll-336.webp', 76, true),
  ('ecc7c8cd38', 'futomaki', 'Futomaki Tobiko Roll', 'Saumon, avocat, surimi, tobiko, cheese 5 Pièces', '49.00', 'MAD', '/menu-hd-onglet16/futomaki-tobiko-roll.png', '/menu-thumbs/menu-hd-onglet16/futomaki-tobiko-roll-224.webp', '/menu-thumbs/menu-hd-onglet16/futomaki-tobiko-roll-336.webp', 77, true),
  ('c0a1b2c3d4', 'california-roll', 'California Cream Cheese', 'Saumon, surimi, avocat, tobiko', '39.00', 'MAD', '/menu-hd-onglet17/california-cream-cheese.png', '/menu-thumbs/menu-hd-onglet17/california-cream-cheese-224.webp', '/menu-thumbs/menu-hd-onglet17/california-cream-cheese-336.webp', 78, true),
  ('d1e2f3a4b5', 'california-roll', 'California Classic', 'Surimi, avocat, concombre, tobiko', '29.00', 'MAD', '/menu-hd-onglet17/california-classic.png', '/menu-thumbs/menu-hd-onglet17/california-classic-224.webp', '/menu-thumbs/menu-hd-onglet17/california-classic-336.webp', 79, true),
  ('e2f3a4b5c6', 'california-roll', 'California Shake Yaki', 'Saumon cuit, avocat, ciboulette', '34.00', 'MAD', '/menu-hd-onglet17/california-shake-yaki.png', '/menu-thumbs/menu-hd-onglet17/california-shake-yaki-224.webp', '/menu-thumbs/menu-hd-onglet17/california-shake-yaki-336.webp', 80, true),
  ('cc76387393', 'california-roll', 'California Saumon Avocat', 'Saumon, avocat, sésame', '34.00', 'MAD', '/menu-hd-onglet17/california-saumon-avocat.png', '/menu-thumbs/menu-hd-onglet17/california-saumon-avocat-224.webp', '/menu-thumbs/menu-hd-onglet17/california-saumon-avocat-336.webp', 81, true),
  ('f3a4b5c6d7', 'california-roll', 'California Eby Tobiko', 'Crevette pané, avocat, tobiko', '39.00', 'MAD', '/menu-hd-onglet17/california-eby-tobiko.png', '/menu-thumbs/menu-hd-onglet17/california-eby-tobiko-224.webp', '/menu-thumbs/menu-hd-onglet17/california-eby-tobiko-336.webp', 82, true),
  ('a4b5c6d7e8', 'california-roll', 'California Eby Fry', 'Crevette tempura, avocat, ciboulette', '34.00', 'MAD', '/menu-hd-onglet17/california-eby-fry.png', '/menu-thumbs/menu-hd-onglet17/california-eby-fry-224.webp', '/menu-thumbs/menu-hd-onglet17/california-eby-fry-336.webp', 83, true),
  ('b5c6d7e8f9', 'california-roll', 'California Chicken Crispy', 'Chicken crispy, avocat, tobiko', '39.00', 'MAD', '/menu-hd-onglet17/california-chicken-crispy.png', '/menu-thumbs/menu-hd-onglet17/california-chicken-crispy-224.webp', '/menu-thumbs/menu-hd-onglet17/california-chicken-crispy-336.webp', 84, true),
  ('84f445e743', 'california-roll', 'California Chicken Eby', 'Poulet pané, crevette pané, cheese, tobiko', '48.00', 'MAD', '/menu-hd-onglet17/california-chicken-eby.png', '/menu-thumbs/menu-hd-onglet17/california-chicken-eby-224.webp', '/menu-thumbs/menu-hd-onglet17/california-chicken-eby-336.webp', 85, true),
  ('302c4c0e8a', 'california-roll', 'California Nara', 'Saumon, crevette pané, avocat, cheese', '48.00', 'MAD', '/menu-hd-onglet17/california-nara.png', '/menu-thumbs/menu-hd-onglet17/california-nara-224.webp', '/menu-thumbs/menu-hd-onglet17/california-nara-336.webp', 86, true),
  ('566b2be815', 'california-roll', 'California Eby Avocado', 'Crevette pané, surimi, saumon, cheese, avocat', '48.00', 'MAD', '/menu-hd-onglet17/california-eby-avocado.png', '/menu-thumbs/menu-hd-onglet17/california-eby-avocado-224.webp', '/menu-thumbs/menu-hd-onglet17/california-eby-avocado-336.webp', 87, true),
  ('79e57587e9', 'california-roll', 'California Rainbow', 'Saumon, avocat, tobiko', '48.00', 'MAD', '/menu-hd-onglet17/california-rainbow.png', '/menu-thumbs/menu-hd-onglet17/california-rainbow-224.webp', '/menu-thumbs/menu-hd-onglet17/california-rainbow-336.webp', 88, true),
  ('fe6a2d104e', 'california-roll', 'Eby Salmon', 'Crevette pané, avocat, saumon, cheese', '48.00', 'MAD', '/menu-hd-onglet17/eby-salmon.jpg', '/menu-thumbs/menu-hd-onglet17/eby-salmon-224.webp', '/menu-thumbs/menu-hd-onglet17/eby-salmon-336.webp', 89, true),
  ('35e32c3559', 'california-roll', 'Fresh Mango', 'Mangue, surimi, avocat, concombre', '36.00', 'MAD', '/menu-hd-onglet17/fresh-mango.jpg', '/menu-thumbs/menu-hd-onglet17/fresh-mango-224.webp', '/menu-thumbs/menu-hd-onglet17/fresh-mango-336.webp', 90, true),
  ('2ce74d5ed1', 'california-roll', 'Shake Saumon', 'Saumon cuit, avocat, saumon', '44.00', 'MAD', '/menu-hd-onglet17/shake-saumon.jpg', '/menu-thumbs/menu-hd-onglet17/shake-saumon-224.webp', '/menu-thumbs/menu-hd-onglet17/shake-saumon-336.webp', 91, true),
  ('5ee8246804', 'special-roll', 'Special Unagui Roll', 'Anguill, eby fry, avocat', '64.00', 'MAD', '/menu-hd-onglet18/special-unagui-roll.png', '/menu-thumbs/menu-hd-onglet18/special-unagui-roll-224.webp', '/menu-thumbs/menu-hd-onglet18/special-unagui-roll-336.webp', 92, true),
  ('7412fc4ec3', 'special-roll', 'Special Triangle Roll', 'Saumon, eby fry, crabe, surimi, avocat', '58.00', 'MAD', '/menu-hd-onglet18/special-triangle-roll.png', '/menu-thumbs/menu-hd-onglet18/special-triangle-roll-224.webp', '/menu-thumbs/menu-hd-onglet18/special-triangle-roll-336.webp', 93, true),
  ('7eeb7d6f83', 'special-roll', 'Special Havana Roll', 'Saumon, eby fry, mangue, surimi, cheese, tobiko', '54.00', 'MAD', '/menu-hd-onglet18/special-havana-roll.png', '/menu-thumbs/menu-hd-onglet18/special-havana-roll-224.webp', '/menu-thumbs/menu-hd-onglet18/special-havana-roll-336.webp', 94, true),
  ('a1b2c3d4e6', 'special-roll', 'Special Goma Roll', 'Saumon, avocat, goma wakamé', '49.00', 'MAD', '/menu-hd-onglet18/special-goma-roll.png', '/menu-thumbs/menu-hd-onglet18/special-goma-roll-224.webp', '/menu-thumbs/menu-hd-onglet18/special-goma-roll-336.webp', 95, true),
  ('b2c3d4e5f7', 'special-roll', 'Special Gambas Roll', 'Crevette poché, eby fry, surimi, avocat', '49.00', 'MAD', '/menu-hd-onglet18/special-gambas-roll.png', '/menu-thumbs/menu-hd-onglet18/special-gambas-roll-224.webp', '/menu-thumbs/menu-hd-onglet18/special-gambas-roll-336.webp', 96, true),
  ('f6a7b8c9d1', 'special-roll', 'Special Kunafa Roll', 'Saumon, eby fry, avocat, kunafa', '49.00', 'MAD', '/menu-hd-onglet18/special-kunafa-roll.png', '/menu-thumbs/menu-hd-onglet18/special-kunafa-roll-224.webp', '/menu-thumbs/menu-hd-onglet18/special-kunafa-roll-336.webp', 97, true),
  ('a7b8c9d0e2', 'special-roll', 'Special Naruto Roll', 'Crevettes, eby fry', '45.00', 'MAD', '/menu-hd-onglet18/special-naruto-roll.jpg', '/menu-thumbs/menu-hd-onglet18/special-naruto-roll-224.webp', '/menu-thumbs/menu-hd-onglet18/special-naruto-roll-336.webp', 98, true),
  ('47cc3a1126', 'special-roll', 'Special Palawan', 'Saumon flambé, saumon, mangue, avocat', '58.00', 'MAD', '/menu-hd-onglet18/special-palawan.jpg', '/menu-thumbs/menu-hd-onglet18/special-palawan-224.webp', '/menu-thumbs/menu-hd-onglet18/special-palawan-336.webp', 99, true),
  ('f466c46a8f', 'special-roll', 'Special Pavot Roll', 'Saumon pané, crabe, mangue, pavot', '49.00', 'MAD', '/menu-hd-onglet18/special-pavot-roll.jpg', '/menu-thumbs/menu-hd-onglet18/special-pavot-roll-224.webp', '/menu-thumbs/menu-hd-onglet18/special-pavot-roll-336.webp', 100, true),
  ('3442a25d4d', 'special-roll', 'Special Green Tiger', 'Eby fry, surimi épicé, avocat', '44.00', 'MAD', '/menu-hd-onglet18/special-green-tiger.jpg', '/menu-thumbs/menu-hd-onglet18/special-green-tiger-224.webp', '/menu-thumbs/menu-hd-onglet18/special-green-tiger-336.webp', 101, true),
  ('c1abc56904', 'special-roll', 'Special Exotic Unagui', 'Anguille, saumon, surimi, mangue', '64.00', 'MAD', '/menu-hd-onglet18/special-exotic-unagui.jpg', '/menu-thumbs/menu-hd-onglet18/special-exotic-unagui-224.webp', '/menu-thumbs/menu-hd-onglet18/special-exotic-unagui-336.webp', 102, true),
  ('449ca2a7f1', 'special-roll', 'Special Mango Tango', 'Crevettes, saumon, mangue, avocat, tobiko', '52.00', 'MAD', '/menu-hd-onglet18/special-mango-tango.jpg', '/menu-thumbs/menu-hd-onglet18/special-mango-tango-224.webp', '/menu-thumbs/menu-hd-onglet18/special-mango-tango-336.webp', 103, true),
  ('53f1432678', 'special-roll', 'Special Spider Roll', 'Eby fry, poireaux, fondue de gouda, kunafa', '44.00', 'MAD', '/menu-hd-onglet18/special-spider-roll.jpg', '/menu-thumbs/menu-hd-onglet18/special-spider-roll-224.webp', '/menu-thumbs/menu-hd-onglet18/special-spider-roll-336.webp', 104, true),
  ('101f7551db', 'special-roll', 'Special Tahiti Roll', 'Eby fry, crabe mariné, avocat, mangue', '44.00', 'MAD', '/menu-hd-onglet18/special-tahiti-roll.jpg', '/menu-thumbs/menu-hd-onglet18/special-tahiti-roll-224.webp', '/menu-thumbs/menu-hd-onglet18/special-tahiti-roll-336.webp', 105, true),
  ('11b8f36cb5', 'aromaki', 'Aromaki Ibiza', 'Saumon, surimi, crevettes pané, avocat, crabe, cheese, tobiko', '64.00', 'MAD', '/menu-hd-onglet19/aromaki-ibiza.png', '/menu-thumbs/menu-hd-onglet19/aromaki-ibiza-224.webp', '/menu-thumbs/menu-hd-onglet19/aromaki-ibiza-336.webp', 106, true),
  ('4da542fb7e', 'aromaki', 'Aromaki Kyoto', 'Saumon, crabe, surimi, mangue, cheese, tobiko', '59.00', 'MAD', '/menu-hd-onglet19/aromaki-kyoto.png', '/menu-thumbs/menu-hd-onglet19/aromaki-kyoto-224.webp', '/menu-thumbs/menu-hd-onglet19/aromaki-kyoto-336.webp', 107, true),
  ('be681d7f41', 'aromaki', 'Aromaki Rio', 'Saumon, surimi, crevettes pané, cheese, tobiko', '59.00', 'MAD', '/menu-hd-onglet19/aromaki-rio.png', '/menu-thumbs/menu-hd-onglet19/aromaki-rio-224.webp', '/menu-thumbs/menu-hd-onglet19/aromaki-rio-336.webp', 108, true),
  ('dabf870bd3', 'aromaki', 'Aromaki Tropicale', 'Crabe, crevettes pané, avocat, mangue, cheese, tobiko', '59.00', 'MAD', '/menu-hd-onglet19/aromaki-tropicale.png', '/menu-thumbs/menu-hd-onglet19/aromaki-tropicale-224.webp', '/menu-thumbs/menu-hd-onglet19/aromaki-tropicale-336.webp', 109, true),
  ('4646423648', 'aromaki', 'Aromaki Honolulu', 'Saumon, surimi, avocat, saumon mariné, cheese, tobiko', '59.00', 'MAD', '/menu-hd-onglet19/aromaki-honolulu.png', '/menu-thumbs/menu-hd-onglet19/aromaki-honolulu-224.webp', '/menu-thumbs/menu-hd-onglet19/aromaki-honolulu-336.webp', 110, true),
  ('cae1232225', 'aromaki', 'Aromaki Exotique', 'Saumon, mangue, avocat, laitue, cheese, tobiko', '54.00', 'MAD', '/menu-hd-onglet19/aromaki-exotique.png', '/menu-thumbs/menu-hd-onglet19/aromaki-exotique-224.webp', '/menu-thumbs/menu-hd-onglet19/aromaki-exotique-336.webp', 111, true),
  ('6af2df4ee9', 'aromaki', 'Aromaki Saumon', 'Saumon, surimi, avocat, cheese, tobiko', '54.00', 'MAD', '/menu-hd-onglet19/aromaki-saumon.png', '/menu-thumbs/menu-hd-onglet19/aromaki-saumon-224.webp', '/menu-thumbs/menu-hd-onglet19/aromaki-saumon-336.webp', 112, true),
  ('85abca6325', 'aromaki', 'Aromaki Panama', 'Saumon, surimi, goma wakamé, avocat, cheese, tobiko', '54.00', 'MAD', '/menu-hd-onglet19/aromaki-panama.png', '/menu-thumbs/menu-hd-onglet19/aromaki-panama-224.webp', '/menu-thumbs/menu-hd-onglet19/aromaki-panama-336.webp', 113, true),
  ('551465cab5', 'aromaki', 'Aromaki Crevettes', 'Crevettes pané, surimi, avocat, cheese, tobiko', '54.00', 'MAD', '/menu-hd-onglet19/aromaki-crevettes.png', '/menu-thumbs/menu-hd-onglet19/aromaki-crevettes-224.webp', '/menu-thumbs/menu-hd-onglet19/aromaki-crevettes-336.webp', 114, true),
  ('89b5ce5b7a', 'aromaki', 'Aromaki Printemps Saumon', 'Saumon, surimi, avocat, cheese, tobiko', '54.00', 'MAD', '/menu-hd-onglet19/aromaki-printemps-saumon.png', '/menu-thumbs/menu-hd-onglet19/aromaki-printemps-saumon-224.webp', '/menu-thumbs/menu-hd-onglet19/aromaki-printemps-saumon-336.webp', 115, true),
  ('02d2e17d1c', 'aromaki', 'Aromaki Hawai', 'Saumon, mangue, avocat, surimi, cheese, tobiko', '54.00', 'MAD', '/menu-hd-onglet19/aromaki-hawai.png', '/menu-thumbs/menu-hd-onglet19/aromaki-hawai-224.webp', '/menu-thumbs/menu-hd-onglet19/aromaki-hawai-336.webp', 116, true),
  ('fff5c41eda', 'aromaki', 'Aromaki Oslo', 'Saumon, mangue, goma wakamé, cheese, tobiko', '54.00', 'MAD', '/menu-hd-onglet19/aromaki-oslo.jpg', '/menu-thumbs/menu-hd-onglet19/aromaki-oslo-224.webp', '/menu-thumbs/menu-hd-onglet19/aromaki-oslo-336.webp', 117, true),
  ('412918d0e5', 'aromaki', 'Aromaki Antalya', 'Saumon, crabe, mangue, laitue, cheese, tobiko', '59.00', 'MAD', '/menu-hd-onglet19/aromaki-antalya.jpg', '/menu-thumbs/menu-hd-onglet19/aromaki-antalya-224.webp', '/menu-thumbs/menu-hd-onglet19/aromaki-antalya-336.webp', 118, true),
  ('77e046cbe4', 'aromaki', 'Aromaki Marbella', 'Saumon, avocat, concombre, cheese, tobiko', '54.00', 'MAD', '/menu-hd-onglet19/aromaki-marbella.jpg', '/menu-thumbs/menu-hd-onglet19/aromaki-marbella-224.webp', '/menu-thumbs/menu-hd-onglet19/aromaki-marbella-336.webp', 119, true),
  ('e41a8a69ca', 'blossom', 'Blossom Ceviché Roll', 'Saumon, mangue, avocat, surimi, tobiko, sésame', '68.00', 'MAD', '/menu-hd-onglet20/blossom-ceviche-roll.jpg', '/menu-thumbs/menu-hd-onglet20/blossom-ceviche-roll-224.webp', '/menu-thumbs/menu-hd-onglet20/blossom-ceviche-roll-336.webp', 120, true),
  ('5347977dbc', 'blossom', 'Blossom Hawai', 'Eby fry, crabe, avocat, mangue, tobiko', '62.00', 'MAD', '/menu-hd-onglet20/blossom-hawai.jpg', '/menu-thumbs/menu-hd-onglet20/blossom-hawai-224.webp', '/menu-thumbs/menu-hd-onglet20/blossom-hawai-336.webp', 121, true),
  ('2d6c4738f9', 'blossom', 'Blossom New York', 'Saumon pané, crevettes, cheese, tobiko', '62.00', 'MAD', '/menu-hd-onglet20/blossom-new-york.jpg', '/menu-thumbs/menu-hd-onglet20/blossom-new-york-224.webp', '/menu-thumbs/menu-hd-onglet20/blossom-new-york-336.webp', 122, true),
  ('f84280a0f7', 'blossom', 'Blossom Boston', 'Eby fry, avocat, cheese, crabe, poireaux, tobiko', '64.00', 'MAD', '/menu-hd-onglet20/blossom-boston.jpg', '/menu-thumbs/menu-hd-onglet20/blossom-boston-224.webp', '/menu-thumbs/menu-hd-onglet20/blossom-boston-336.webp', 123, true),
  ('12117b00b9', 'blossom', 'Blossom Eby Roll', 'Crevettes, saumon, avocat, cheese', '64.00', 'MAD', '/menu-hd-onglet20/blossom-eby-roll.jpg', '/menu-thumbs/menu-hd-onglet20/blossom-eby-roll-224.webp', '/menu-thumbs/menu-hd-onglet20/blossom-eby-roll-336.webp', 124, true),
  ('cb9324ca52', 'blossom', 'Blossom Tokyo', 'Surimi pané, saumon, mangue, cheese, tobiko', '59.00', 'MAD', '/menu-hd-onglet20/blossom-tokyo.jpg', '/menu-thumbs/menu-hd-onglet20/blossom-tokyo-224.webp', '/menu-thumbs/menu-hd-onglet20/blossom-tokyo-336.webp', 125, true),
  ('ace54559af', 'blossom', 'Blossom Saumon Braisé', 'Saumon braisé, avocat, cheese', '59.00', 'MAD', '/menu-hd-onglet20/blossom-saumon-braise.jpg', '/menu-thumbs/menu-hd-onglet20/blossom-saumon-braise-224.webp', '/menu-thumbs/menu-hd-onglet20/blossom-saumon-braise-336.webp', 126, true),
  ('c435723d4c', 'blossom', 'Blossom Bali', 'Saumon mariné, surimi, avocat, cheese, sésame', '54.00', 'MAD', '/menu-hd-onglet20/blossom-bali.jpg', '/menu-thumbs/menu-hd-onglet20/blossom-bali-224.webp', '/menu-thumbs/menu-hd-onglet20/blossom-bali-336.webp', 127, true),
  ('e463b20218', 'blossom', 'Blossom Bonzaï', 'Anguille, avocat, surimi, cheese, sésame', '64.00', 'MAD', '/menu-hd-onglet20/blossom-bonzai.jpg', '/menu-thumbs/menu-hd-onglet20/blossom-bonzai-224.webp', '/menu-thumbs/menu-hd-onglet20/blossom-bonzai-336.webp', 128, true),
  ('0433bbd53c', 'blossom', 'Blossom Mango Saumon', 'Saumon mariné, mangue, avocat, tobiko', '59.00', 'MAD', '/menu-hd-onglet20/blossom-mango-saumon.jpg', '/menu-thumbs/menu-hd-onglet20/blossom-mango-saumon-224.webp', '/menu-thumbs/menu-hd-onglet20/blossom-mango-saumon-336.webp', 129, true),
  ('6d09d7bf8d', 'blossom', 'Blossom Crabe', 'Crabe mariné, saumon, mangue, cheese', '64.00', 'MAD', '/menu-hd-onglet20/blossom-crabe.jpg', '/menu-thumbs/menu-hd-onglet20/blossom-crabe-224.webp', '/menu-thumbs/menu-hd-onglet20/blossom-crabe-336.webp', 130, true),
  ('cf8623ce70', 'blossom', 'Blossom Green Salmon', 'Saumon, avocat, concombre', '55.00', 'MAD', '/menu-hd-onglet20/blossom-green-salmon.jpg', '/menu-thumbs/menu-hd-onglet20/blossom-green-salmon-224.webp', '/menu-thumbs/menu-hd-onglet20/blossom-green-salmon-336.webp', 131, true),
  ('f33f401dd2', 'blossom', 'Blossom Cheezy Salmon', 'Saumon, avocat, cheese, tobiko', '59.00', 'MAD', '/menu-hd-onglet20/blossom-cheezy-salmon.jpg', '/menu-thumbs/menu-hd-onglet20/blossom-cheezy-salmon-224.webp', '/menu-thumbs/menu-hd-onglet20/blossom-cheezy-salmon-336.webp', 132, true),
  ('cd27240259', 'blossom', 'Blossom Exotic', 'Saumon, avocat, mangue, cheese', '59.00', 'MAD', '/menu-hd-onglet20/blossom-exotic.jpg', '/menu-thumbs/menu-hd-onglet20/blossom-exotic-224.webp', '/menu-thumbs/menu-hd-onglet20/blossom-exotic-336.webp', 133, true),
  ('cec5e70b6a', 'premium', 'Premium Cancun', 'Saumon, eby fry, surimi, avocat, laitue, cheese', '65.00', 'MAD', '/menu-hd-onglet21/premium-cancun.jpg', '/menu-thumbs/menu-hd-onglet21/premium-cancun-224.webp', '/menu-thumbs/menu-hd-onglet21/premium-cancun-336.webp', 134, true),
  ('6c2ba70a6f', 'premium', 'Premium Krabi Roll', 'Saumon, eby fry, surimi crabe, avocat, goma wakamé', '69.00', 'MAD', '/menu-hd-onglet21/premium-krabi-roll.jpg', '/menu-thumbs/menu-hd-onglet21/premium-krabi-roll-224.webp', '/menu-thumbs/menu-hd-onglet21/premium-krabi-roll-336.webp', 135, true),
  ('c6bf1f1759', 'premium', 'Premium Fuji Roll', 'Saumon, eby fry, saumon cuit, mangue', '69.00', 'MAD', '/menu-hd-onglet21/premium-fuji-roll.jpg', '/menu-thumbs/menu-hd-onglet21/premium-fuji-roll-224.webp', '/menu-thumbs/menu-hd-onglet21/premium-fuji-roll-336.webp', 136, true),
  ('b1b1b0e1ba', 'premium', 'Premium Pink Salmon', 'Crevette poché, saumon, surimi crevette pané', '69.00', 'MAD', '/menu-hd-onglet21/premium-pink-salmon.jpg', '/menu-thumbs/menu-hd-onglet21/premium-pink-salmon-224.webp', '/menu-thumbs/menu-hd-onglet21/premium-pink-salmon-336.webp', 137, true),
  ('82bc3899c0', 'premium', 'Premium Exotica Roll', 'Double eby fry, saumon, surimi, avocat, wakamé', '69.00', 'MAD', '/menu-hd-onglet21/premium-exotica-roll.jpg', '/menu-thumbs/menu-hd-onglet21/premium-exotica-roll-224.webp', '/menu-thumbs/menu-hd-onglet21/premium-exotica-roll-336.webp', 138, true),
  ('2aacef48a6', 'premium', 'Premium Pataya', 'Double crevette pané, surimi, saumon, mangue, tobiko, ciboulette', '69.00', 'MAD', '/menu-hd-onglet21/premium-pataya.jpg', '/menu-thumbs/menu-hd-onglet21/premium-pataya-224.webp', '/menu-thumbs/menu-hd-onglet21/premium-pataya-336.webp', 139, true),
  ('fd173daf85', 'premium', 'Premium Sirena Roll', 'Eby fry, saumon flambé, fondue de gouda', '69.00', 'MAD', '/menu-hd-onglet21/premium-sirena-roll.jpg', '/menu-thumbs/menu-hd-onglet21/premium-sirena-roll-224.webp', '/menu-thumbs/menu-hd-onglet21/premium-sirena-roll-336.webp', 140, true),
  ('ef3a2da619', 'premium', 'Premium Salmon Tataki', 'Saumon cuit, saumon braisé, saumon mariné, surimi, avocat', '69.00', 'MAD', '/menu-hd-onglet21/premium-salmon-tataki.jpg', '/menu-thumbs/menu-hd-onglet21/premium-salmon-tataki-224.webp', '/menu-thumbs/menu-hd-onglet21/premium-salmon-tataki-336.webp', 141, true),
  ('ffddedcf35', 'premium', 'Premium Bora Bora', 'Saumon, mangue, wakamé, avocat, surimi, saumon cuit', '69.00', 'MAD', '/menu-hd-onglet21/premium-bora-bora.jpg', '/menu-thumbs/menu-hd-onglet21/premium-bora-bora-224.webp', '/menu-thumbs/menu-hd-onglet21/premium-bora-bora-336.webp', 142, true),
  ('52d169b9dd', 'premium', 'Premium Exotic Salmon', 'Saumon, mangue, eby fry, surimi, saumon cuit, tobiko', '69.00', 'MAD', '/menu-hd-onglet21/premium-exotic-salmon.jpg', '/menu-thumbs/menu-hd-onglet21/premium-exotic-salmon-224.webp', '/menu-thumbs/menu-hd-onglet21/premium-exotic-salmon-336.webp', 143, true),
  ('df7dc34617', 'makito-fry', 'Makito Saumon Epicé', 'Saumon épicé, fondu de gouda 6 Pièces', '52.00', 'MAD', '/menu-hd-onglet22/makito-saumon-epice.jpg', '/menu-thumbs/menu-hd-onglet22/makito-saumon-epice-224.webp', '/menu-thumbs/menu-hd-onglet22/makito-saumon-epice-336.webp', 144, true),
  ('e6820a6ec3', 'makito-fry', 'Makito Crevettes', 'Crevette mariné, gambas, fondu de gouda 6 Pièces', '49.00', 'MAD', '/menu-hd-onglet22/makito-crevettes.jpg', '/menu-thumbs/menu-hd-onglet22/makito-crevettes-224.webp', '/menu-thumbs/menu-hd-onglet22/makito-crevettes-336.webp', 145, true),
  ('7256c43d8d', 'makito-fry', 'Makito Anguille', 'Anguille marinée, fondu de gouda 6 Pièces', '56.00', 'MAD', '/menu-hd-onglet22/makito-anguille.jpg', '/menu-thumbs/menu-hd-onglet22/makito-anguille-224.webp', '/menu-thumbs/menu-hd-onglet22/makito-anguille-336.webp', 146, true),
  ('0ee40fc997', 'makito-fry', 'Makito Crabe', 'Crabe mariné, fondu de gouda 6 Pièces', '55.00', 'MAD', '/menu-hd-onglet22/makito-crabe.jpg', '/menu-thumbs/menu-hd-onglet22/makito-crabe-224.webp', '/menu-thumbs/menu-hd-onglet22/makito-crabe-336.webp', 147, true),
  ('112f439dc8', 'makito-fry', 'Makito Saumon', 'Saumon, fondu de gouda 6 Pièces', '49.00', 'MAD', '/menu-hd-onglet22/makito-saumon.jpg', '/menu-thumbs/menu-hd-onglet22/makito-saumon-224.webp', '/menu-thumbs/menu-hd-onglet22/makito-saumon-336.webp', 148, true),
  ('df8e4b755c', 'crispy-roll', 'Crispy Red White', 'Saumon, crevette, poisson, cheese, tobiko 6 Pièces', '62.00', 'MAD', '/menu-hd-onglet23/crispy-red-white.jpg', '/menu-thumbs/menu-hd-onglet23/crispy-red-white-224.webp', '/menu-thumbs/menu-hd-onglet23/crispy-red-white-336.webp', 149, true),
  ('007985588c', 'crispy-roll', 'Crispy Sakura', 'Saumon, surimi, tobiko, avocat 6 Pièces', '56.00', 'MAD', '/menu-hd-onglet23/crispy-sakura.jpg', '/menu-thumbs/menu-hd-onglet23/crispy-sakura-224.webp', '/menu-thumbs/menu-hd-onglet23/crispy-sakura-336.webp', 150, true),
  ('f0b86623a1', 'crispy-roll', 'Crispy Eby Chicken Fry', 'Poulet pané, crevette pané, avocat, surimi 6 Pièces', '58.00', 'MAD', '/menu-hd-onglet23/crispy-eby-chicken-fry.jpg', '/menu-thumbs/menu-hd-onglet23/crispy-eby-chicken-fry-224.webp', '/menu-thumbs/menu-hd-onglet23/crispy-eby-chicken-fry-336.webp', 151, true),
  ('deb56ea325', 'crispy-roll', 'Crispy Cheesy Fish', 'Poisson pané, surimi pané, fondu de gouda 6 pièces', '54.00', 'MAD', '/menu-hd-onglet23/crispy-cheesy-fish.jpg', '/menu-thumbs/menu-hd-onglet23/crispy-cheesy-fish-224.webp', '/menu-thumbs/menu-hd-onglet23/crispy-cheesy-fish-336.webp', 152, true),
  ('9f730f7289', 'crispy-roll', 'Crispy Saumon Tempura', 'Saumon tempura, avocat, surimi, cheese, tobiko 6 Pièces', '52.00', 'MAD', '/menu-hd-onglet23/crispy-saumon-tempura.jpg', '/menu-thumbs/menu-hd-onglet23/crispy-saumon-tempura-224.webp', '/menu-thumbs/menu-hd-onglet23/crispy-saumon-tempura-336.webp', 153, true),
  ('06066ec740', 'crispy-roll', 'Crispy Saumon Cuit', 'Saumon cuit, avocat 6 Pièces', '52.00', 'MAD', '/menu-hd-onglet23/crispy-saumon-cuit.jpg', '/menu-thumbs/menu-hd-onglet23/crispy-saumon-cuit-224.webp', '/menu-thumbs/menu-hd-onglet23/crispy-saumon-cuit-336.webp', 154, true),
  ('e3c612287f', 'crispy-roll', 'Crispy Crevette Avocat', 'Crevette, avocat, surimi 6 Pièces', '52.00', 'MAD', '/menu-hd-onglet23/crispy-crevette-avocat.jpg', '/menu-thumbs/menu-hd-onglet23/crispy-crevette-avocat-224.webp', '/menu-thumbs/menu-hd-onglet23/crispy-crevette-avocat-336.webp', 155, true),
  ('c1d4661e91', 'crispy-roll', 'Crispy Saumon Cheese', 'Saumon, tobiko, cheese 6 Pièces', '52.00', 'MAD', '/menu-hd-onglet23/crispy-saumon-cheese.jpg', '/menu-thumbs/menu-hd-onglet23/crispy-saumon-cheese-224.webp', '/menu-thumbs/menu-hd-onglet23/crispy-saumon-cheese-336.webp', 156, true),
  ('5ec25676a2', 'crunchy-roll', 'Crunchy Saumon Avocat', 'saumon, surimi, avocat, tobiko, cheese 6 Pièces', '59.00', 'MAD', '/menu-hd-onglet24/crunchy-saumon-avocat.jpg', '/menu-thumbs/menu-hd-onglet24/crunchy-saumon-avocat-224.webp', '/menu-thumbs/menu-hd-onglet24/crunchy-saumon-avocat-336.webp', 157, true),
  ('fc97991608', 'crunchy-roll', 'Crunchy Eby Tempura', 'Crevette pané, saumon, concombre, tobiko, cheese 6 Pièces', '59.00', 'MAD', '/menu-hd-onglet24/crunchy-eby-tempura.jpg', '/menu-thumbs/menu-hd-onglet24/crunchy-eby-tempura-224.webp', '/menu-thumbs/menu-hd-onglet24/crunchy-eby-tempura-336.webp', 158, true),
  ('b2336232f7', 'crunchy-roll', 'Crunchy Casablanca', 'Crevettes pané, crabe, mangue, cheese, tobiko 6 Pièces', '59.00', 'MAD', '/menu-hd-onglet24/crunchy-casablanca.jpg', '/menu-thumbs/menu-hd-onglet24/crunchy-casablanca-224.webp', '/menu-thumbs/menu-hd-onglet24/crunchy-casablanca-336.webp', 159, true),
  ('b6bb8210a3', 'crunchy-roll', 'Crunchy Tiger Fry', 'Crevette pané, surimi, avocat, cheese, tobiko 6 Pièces', '59.00', 'MAD', '/menu-hd-onglet24/crunchy-tiger-fry.jpg', '/menu-thumbs/menu-hd-onglet24/crunchy-tiger-fry-224.webp', '/menu-thumbs/menu-hd-onglet24/crunchy-tiger-fry-336.webp', 160, true),
  ('e8077d2295', 'crunchy-roll', 'Crunchy Dragon Eyes', 'Saumon, poireaux, carottes, ciboulette, cheese, tobiko 6 Pièces', '55.00', 'MAD', '/menu-hd-onglet24/crunchy-dragon-eyes.jpg', '/menu-thumbs/menu-hd-onglet24/crunchy-dragon-eyes-224.webp', '/menu-thumbs/menu-hd-onglet24/crunchy-dragon-eyes-336.webp', 161, true),
  ('e3a96c288b', 'crunchy-roll', 'Crunchy Pacific', 'Crevette pané, surimi pané, cheese, tobiko 6 Pièces', '55.25', 'MAD', '/menu-hd-onglet24/crunchy-pacific.jpg', '/menu-thumbs/menu-hd-onglet24/crunchy-pacific-224.webp', '/menu-thumbs/menu-hd-onglet24/crunchy-pacific-336.webp', 162, true),
  ('3583d51b73', 'crunchy-roll', 'Crunchy Fry Eby Fry', 'Crevette pané, avocat, cheese 6 Pièces', '55.25', 'MAD', '/menu-hd-onglet24/crunchy-fry-eby-fry.jpg', '/menu-thumbs/menu-hd-onglet24/crunchy-fry-eby-fry-224.webp', '/menu-thumbs/menu-hd-onglet24/crunchy-fry-eby-fry-336.webp', 163, true),
  ('45bca3a281', 'crunchy-roll', 'Crunchy Fry Salmon Fry', 'Saumon cuit, cheese, tobiko 6 Pièces', '55.25', 'MAD', '/menu-hd-onglet24/crunchy-fry-salmon-fry.jpg', '/menu-thumbs/menu-hd-onglet24/crunchy-fry-salmon-fry-224.webp', '/menu-thumbs/menu-hd-onglet24/crunchy-fry-salmon-fry-336.webp', 164, true),
  ('53578ea799', 'crunchy-roll', 'Crunchy Osaka', 'Saumon, surimi, wakamé 6 Pièces', '59.00', 'MAD', '/menu-hd-onglet24/crunchy-osaka.jpg', '/menu-thumbs/menu-hd-onglet24/crunchy-osaka-224.webp', '/menu-thumbs/menu-hd-onglet24/crunchy-osaka-336.webp', 165, true),
  ('083ac320dd', 'wok-thai', 'Wok', 'Nouilles — sauce au choix : oyster, teriyaki, aigre doux, sweet chili.', '49.00', 'MAD', '/menu-hd-onglet25/wok-nouilles.jpg', '/menu-thumbs/menu-hd-onglet25/wok-nouilles-224.webp', '/menu-thumbs/menu-hd-onglet25/wok-nouilles-336.webp', 166, true),
  ('0c48c8093e', 'wok-thai', 'Vermicelle', 'Vermicelle — sauce au choix : oyster, teriyaki, aigre doux, sweet chili.', '49.00', 'MAD', '/menu-hd-onglet25/vermicelle.jpg', '/menu-thumbs/menu-hd-onglet25/vermicelle-224.webp', '/menu-thumbs/menu-hd-onglet25/vermicelle-336.webp', 167, true),
  ('5c227884f6', 'wok-thai', 'Riz Cantonais', 'Riz cantonais.', '49.00', 'MAD', '/menu-hd-onglet25/riz-cantonais.jpg', '/menu-thumbs/menu-hd-onglet25/riz-cantonais-224.webp', '/menu-thumbs/menu-hd-onglet25/riz-cantonais-336.webp', 168, true),
  ('382bef2bb1', 'wok-thai', 'Pad Thaï', '', '64.00', 'MAD', '/menu-hd-onglet25/pad-thai.jpg', '/menu-thumbs/menu-hd-onglet25/pad-thai-224.webp', '/menu-thumbs/menu-hd-onglet25/pad-thai-336.webp', 169, true),
  ('cd6fcbb51e', 'plats-thai', 'Boeuf Bulgogi', 'Boeuf, gingembre, huile de sésame, Ail, sauce cacahuète, cacahuètes (servi avec du riz)', '79.00', 'MAD', '/menu-hd-onglet26/boeuf-bulgogi.jpg', '/menu-thumbs/menu-hd-onglet26/boeuf-bulgogi-224.webp', '/menu-thumbs/menu-hd-onglet26/boeuf-bulgogi-336.webp', 170, true),
  ('36987b1e67', 'plats-thai', 'Red Curry Thaï', 'Lait de coco, sauce curry thaï poivrons, champignon, brocolis, carottes, courgettes, échalotes (servi avec du riz)', '64.00', 'MAD', '/menu-hd-onglet26/red-curry-thai.jpg', '/menu-thumbs/menu-hd-onglet26/red-curry-thai-224.webp', '/menu-thumbs/menu-hd-onglet26/red-curry-thai-336.webp', 171, true),
  ('9eba998f82', 'plats-thai', 'Ananas Aigre Doux', 'Ananas, poivrons, champignon noir, champignon paris, noix de cajou, sauce aigre doux (servi avec du riz)', '64.00', 'MAD', '/menu-hd-onglet26/ananas-aigre-doux.jpg', '/menu-thumbs/menu-hd-onglet26/ananas-aigre-doux-224.webp', '/menu-thumbs/menu-hd-onglet26/ananas-aigre-doux-336.webp', 172, true),
  ('0755e5b16d', 'plats-thai', 'Corean Chicken', 'Poulet caramélisé , servi avec nouilles ou riz sauté aux légumes', '69.00', 'MAD', '/menu-hd-onglet26/corean-chicken.jpg', '/menu-thumbs/menu-hd-onglet26/corean-chicken-224.webp', '/menu-thumbs/menu-hd-onglet26/corean-chicken-336.webp', 173, true),
  ('9443eb67b5', 'plats-thai', 'Saté', 'servi avec du riz', '69.00', 'MAD', '/menu-hd-onglet26/sate.jpg', '/menu-thumbs/menu-hd-onglet26/sate-224.webp', '/menu-thumbs/menu-hd-onglet26/sate-336.webp', 174, true),
  ('a8016335cd', 'plats-thai', 'Basilic Thaï', 'Basilic, poivrons, brocolis, carottes, gingembre, échalotes, champignons frais, sauce huîtres.', '69.00', 'MAD', '/menu-hd-onglet26/basilic-thai.jpg', '/menu-thumbs/menu-hd-onglet26/basilic-thai-224.webp', '/menu-thumbs/menu-hd-onglet26/basilic-thai-336.webp', 175, true),
  ('4afcd30489', 'plats-thai', 'Champignon & Bambou', 'Champignons de Paris, pousses de bambou, champignon noir, échalotes, sauce huîtres.', '69.00', 'MAD', '/menu-hd-onglet26/champignon-bambou.jpg', '/menu-thumbs/menu-hd-onglet26/champignon-bambou-224.webp', '/menu-thumbs/menu-hd-onglet26/champignon-bambou-336.webp', 176, true),
  ('9e1d2c99ca', 'plats-thai', 'Chop Suey', 'Brocolis, haricots verts, courgettes, carottes, germes de soja, épis de maïs, mix poivrons, gingembre, champignons de Paris, chou, ail.', '69.00', 'MAD', '/menu-hd-onglet26/chop-suey.jpg', '/menu-thumbs/menu-hd-onglet26/chop-suey-224.webp', '/menu-thumbs/menu-hd-onglet26/chop-suey-336.webp', 177, true),
  ('55088e9b04', 'plats-thai', 'Pavé de Saumon', 'Pavé de saumon à la sauce ail citron gingembre ou à la sauce teriyaki accompagné de riz et légumes.', '89.00', 'MAD', '/menu-hd-onglet26/pave-de-saumon.jpg', '/menu-thumbs/menu-hd-onglet26/pave-de-saumon-224.webp', '/menu-thumbs/menu-hd-onglet26/pave-de-saumon-336.webp', 178, true),
  ('18b0c7ab53', 'plats-thai', 'Chicken Katsu', 'Poulet crunchy accompagné de légumes et riz et sauce katsu.', '74.00', 'MAD', '/menu-hd-onglet26/chicken-katsu.jpg', '/menu-thumbs/menu-hd-onglet26/chicken-katsu-224.webp', '/menu-thumbs/menu-hd-onglet26/chicken-katsu-336.webp', 179, true),
  ('1568a2e365', 'plats-thai', 'Teppanyaki', 'Grillé à la sauce teriyaki accompagné de légumes et riz.', '69.00', 'MAD', '/menu-hd-onglet26/teppanyaki.jpg', '/menu-thumbs/menu-hd-onglet26/teppanyaki-224.webp', '/menu-thumbs/menu-hd-onglet26/teppanyaki-336.webp', 180, true),
  ('d99671dda4', 'assortiments', 'Prime Box 16 pcs', '6 aromaki saumon, 4 cream cheese, 6 maki saumon.', '119.00', 'MAD', '/menu-hd-onglet27/assort16-prime-box.png', '/menu-thumbs/menu-hd-onglet27/assort16-prime-box-224.webp', '/menu-thumbs/menu-hd-onglet27/assort16-prime-box-336.webp', 181, true),
  ('f7e59011ae', 'assortiments', 'Funny 16 pcs', '4 cream cheese, 4 eby fry, 6 maki saumon, 2 nigiri saumon.', '119.00', 'MAD', '/menu-hd-onglet27/assort16-funny.png', '/menu-thumbs/menu-hd-onglet27/assort16-funny-224.webp', '/menu-thumbs/menu-hd-onglet27/assort16-funny-336.webp', 182, true),
  ('794bc29deb', 'assortiments', 'Eby Lovers 16 pcs', '4 pacific, 4 ebi fry, 8 aromaki crevettes.', '119.00', 'MAD', '/menu-hd-onglet27/assort16-eby-lovers.png', '/menu-thumbs/menu-hd-onglet27/assort16-eby-lovers-224.webp', '/menu-thumbs/menu-hd-onglet27/assort16-eby-lovers-336.webp', 183, true),
  ('5e0ccaac41', 'assortiments', 'Crunchy Box 16 pcs', '4 fry salmon fry, 4 fry ebi fry, 4 croquette poulet, 4 pacific.', '119.00', 'MAD', '/menu-hd-onglet27/assort16-crunchy-box.png', '/menu-thumbs/menu-hd-onglet27/assort16-crunchy-box-224.webp', '/menu-thumbs/menu-hd-onglet27/assort16-crunchy-box-336.webp', 184, true),
  ('6515d6b542', 'assortiments', 'California Box 16 pcs', '4 classic, 4 chicken crispy, 4 ebi fry, 4 cream cheese.', '119.00', 'MAD', '/menu-hd-onglet27/assort16-california-box.jpg', '/menu-thumbs/menu-hd-onglet27/assort16-california-box-224.webp', '/menu-thumbs/menu-hd-onglet27/assort16-california-box-336.webp', 185, true),
  ('8827d5820f', 'assortiments', 'Aromaki Lovers 24 pcs', '6 aromaki saumon, 6 aromaki crevettes, 6 sunchine, 6 spring roll crevettes.', '255.00', 'MAD', '/menu-hd-onglet28/assort24-aromaki-lovers.png', '/menu-thumbs/menu-hd-onglet28/assort24-aromaki-lovers-224.webp', '/menu-thumbs/menu-hd-onglet28/assort24-aromaki-lovers-336.webp', 186, true),
  ('c9b4e3431d', 'assortiments', 'California Lovers 24 pcs', '4 classic, 4 ebi fry, 4 cream cheese, 4 shake yaki, 4 saumon avocat, 4 chicken crispy.', '255.00', 'MAD', '/menu-hd-onglet28/assort24-california-lovers.png', '/menu-thumbs/menu-hd-onglet28/assort24-california-lovers-224.webp', '/menu-thumbs/menu-hd-onglet28/assort24-california-lovers-336.webp', 187, true),
  ('58c0a31b31', 'assortiments', 'Summer 20 pcs', '4 ebi salmon, 4 green tiger, 4 spider, 6 aromaki crevettes, 2 nigiri saumon.', '255.00', 'MAD', '/menu-hd-onglet28/assort20-summer.png', '/menu-thumbs/menu-hd-onglet28/assort20-summer-224.webp', '/menu-thumbs/menu-hd-onglet28/assort20-summer-336.webp', 188, true),
  ('d2212cb6f2', 'assortiments', 'Crunchy Lovers 24 pcs', '8 pizza saumon mozza, 4 crunchy crevettes, 4 croquette poulet, 4 fry salmon fry, 4 pacific.', '255.00', 'MAD', '/menu-hd-onglet28/assort24-crunchy-lovers.png', '/menu-thumbs/menu-hd-onglet28/assort24-crunchy-lovers-224.webp', '/menu-thumbs/menu-hd-onglet28/assort24-crunchy-lovers-336.webp', 189, true),
  ('941fda2c02', 'assortiments', 'Deluxe 24 pcs', '4 classic, 4 ebi fry, 4 maki saumon, 4 fry ebi fry, 4 fry salmon fry, 4 makito saumon épicé.', '255.00', 'MAD', '/menu-hd-onglet28/assort24-deluxe.png', '/menu-thumbs/menu-hd-onglet28/assort24-deluxe-224.webp', '/menu-thumbs/menu-hd-onglet28/assort24-deluxe-336.webp', 190, true),
  ('a39d62353c', 'assortiments', 'Delice 30 pcs', '6 classic, 4 ebi fry, 4 shake yaki, 4 cream cheese, 6 maki saumon, 4 aromaki saumon, 2 nigiri saumon.', '235.00', 'MAD', '/menu-hd-onglet29/assort30-delice.png', '/menu-thumbs/menu-hd-onglet29/assort30-delice-224.webp', '/menu-thumbs/menu-hd-onglet29/assort30-delice-336.webp', 191, true),
  ('0679c0f898', 'assortiments', 'Enjoy Box 30 pcs', '4 classic, 4 ebi fry, 4 pacific, 4 fry salmon fry, 6 aromaki crevettes, 6 aromaki saumon, 2 nigiri saumon.', '235.00', 'MAD', '/menu-hd-onglet29/assort30-enjoy-box.png', '/menu-thumbs/menu-hd-onglet29/assort30-enjoy-box-224.webp', '/menu-thumbs/menu-hd-onglet29/assort30-enjoy-box-336.webp', 192, true),
  ('267463ea64', 'assortiments', 'Jocker 30 pcs', '6 classic, 6 ebi fry, 4 cream cheese, 4 pacific, 6 fry salmon fry, 4 aromaki crevettes.', '235.00', 'MAD', '/menu-hd-onglet29/assort30-jocker.png', '/menu-thumbs/menu-hd-onglet29/assort30-jocker-224.webp', '/menu-thumbs/menu-hd-onglet29/assort30-jocker-336.webp', 193, true),
  ('59108b5a10', 'assortiments', 'Gourmet 36 pcs', '4 classic, 4 ebi fry, 4 cream cheese, 4 saumon avocat, 4 nara, 4 green tiger, 4 naruto, 4 tahiti, 4 spider.', '295.00', 'MAD', '/menu-hd-onglet30/assort36-gourmet.png', '/menu-thumbs/menu-hd-onglet30/assort36-gourmet-224.webp', '/menu-thumbs/menu-hd-onglet30/assort36-gourmet-336.webp', 194, true),
  ('c800597832', 'assortiments', 'Dream 36 pcs', '4 green tiger, 4 Tahiti, 4 naruto, 4 goma roll, 4 spider, 4 eby salmon, 6 aromaki saumon, 6 aromaki crevettes.', '295.00', 'MAD', '/menu-hd-onglet30/assort36-dream.png', '/menu-thumbs/menu-hd-onglet30/assort36-dream-224.webp', '/menu-thumbs/menu-hd-onglet30/assort36-dream-336.webp', 195, true),
  ('b5dd505e6f', 'assortiments', 'Extasy 40', '4 classic, 4 ebi fry, 4 cream cheese, 4 shake yaki, 4 saumon avocat, 4 chicken crispy, 8 fry salmon fry, 8 pacific. (40 pcs)', '295.00', 'MAD', '/menu-hd-onglet30/assort40-extasy.png', '/menu-thumbs/menu-hd-onglet30/assort40-extasy-224.webp', '/menu-thumbs/menu-hd-onglet30/assort40-extasy-336.webp', 196, true),
  ('b4a12d5c8c', 'assortiments', 'Fiesta 48 pcs', '4 classic, 4 ebi fry, 4 shake yaki, 4 cream cheese, 4 saumon avocat, 4 chicken crispy, 4 pacific, 4 fry salmon fry, 4 fry ebi fry, 6 aromaki saumon, 6 aromaki crevettes.', '355.00', 'MAD', '/menu-hd-onglet31/assort48-fiesta.png', '/menu-thumbs/menu-hd-onglet31/assort48-fiesta-224.webp', '/menu-thumbs/menu-hd-onglet31/assort48-fiesta-336.webp', 197, true),
  ('a4fdedb9b3', 'assortiments', 'Festival 48 pcs', '4 classic, 4 ebi fry, 4 shake yaki, 4 cream cheese, 4 saumon avocat, 8 fry salmon fry, 8 fry ebi fry, 4 chicken crispy, 8 makito saumon epicé.', '355.00', 'MAD', '/menu-hd-onglet31/assort48-festival.png', '/menu-thumbs/menu-hd-onglet31/assort48-festival-224.webp', '/menu-thumbs/menu-hd-onglet31/assort48-festival-336.webp', 198, true),
  ('225dc32819', 'assortiments', 'Happy Box 44 pcs', '4 goma roll, 4 Tahiti, 4 green tiger, 4 ebi salmon, 4 bali, 4 spider, 4 maki saumon épicé, 4 naruto, 6 aromaki crevettes, 6 aromaki saumon.', '355.00', 'MAD', '/menu-hd-onglet31/assort44-happy-box.png', '/menu-thumbs/menu-hd-onglet31/assort44-happy-box-224.webp', '/menu-thumbs/menu-hd-onglet31/assort44-happy-box-336.webp', 199, true),
  ('4a3cdf3348', 'assortiments', 'Carnaval 60 pcs', '4 classic, 4 ebi fry, 4 cream cheese, 4 shake yaki, 4 saumon avocat, 4 chicken crispy, 4 green tiger, 4 aromaki saumon, 4 ebi salmon, 4 aromaki crevettes, 4 tahiti, 4 naruto, 4 goma roll, 8 spider.', '450.00', 'MAD', '/menu-hd-onglet32/assort60-carnaval.png', '/menu-thumbs/menu-hd-onglet32/assort60-carnaval-224.webp', '/menu-thumbs/menu-hd-onglet32/assort60-carnaval-336.webp', 200, true),
  ('10fc49f9b4', 'assortiments', 'Family Box 60 pcs', '4 classic, 4 ebi fry, 4 cream cheese, 4 saumon avocat, 4 green tiger, 4 tahiti, 4 naruto, 4 ebi salmon, 8 fry salmon fry, 8 pacific, 4 aromaki saumon, 8 aromaki crevettes.', '450.00', 'MAD', '/menu-hd-onglet32/assort60-family-box.png', '/menu-thumbs/menu-hd-onglet32/assort60-family-box-224.webp', '/menu-thumbs/menu-hd-onglet32/assort60-family-box-336.webp', 201, true),
  ('5c15472d24', 'desserts', 'Cheese Cake Speculos', 'Cheese Cake Speculos', '39.00', 'MAD', '/menu-hd-onglet33/dessert-cheese-cake-speculos.png', '/menu-thumbs/menu-hd-onglet33/dessert-cheese-cake-speculos-224.webp', '/menu-thumbs/menu-hd-onglet33/dessert-cheese-cake-speculos-336.webp', 202, true),
  ('6bfd43d617', 'desserts', 'Banoffee Pie', 'Banoffee Pie', '34.00', 'MAD', '/menu-hd-onglet33/dessert-banoffee-pie.png', '/menu-thumbs/menu-hd-onglet33/dessert-banoffee-pie-224.webp', '/menu-thumbs/menu-hd-onglet33/dessert-banoffee-pie-336.webp', 203, true),
  ('787c236c7b', 'jus', 'Jus Exotique', 'Exotique', '34.00', 'MAD', '/menu-hd-onglet34/jus-exotique.png', '/menu-thumbs/menu-hd-onglet34/jus-exotique-224.webp', '/menu-thumbs/menu-hd-onglet34/jus-exotique-336.webp', 204, true),
  ('fde993538f', 'jus', 'Jus Fraise', 'Fraise', '32.00', 'MAD', '/menu-hd-onglet34/jus-fraise.png', '/menu-thumbs/menu-hd-onglet34/jus-fraise-224.webp', '/menu-thumbs/menu-hd-onglet34/jus-fraise-336.webp', 205, true),
  ('2b9993080d', 'jus', 'Jus Ananas', 'Ananas', '32.00', 'MAD', '/menu-hd-onglet34/jus-ananas.png', '/menu-thumbs/menu-hd-onglet34/jus-ananas-224.webp', '/menu-thumbs/menu-hd-onglet34/jus-ananas-336.webp', 206, true),
  ('a2b893eb78', 'jus', 'Jus Mangue', 'Mangue', '32.00', 'MAD', '/menu-hd-onglet34/jus-mangue.png', '/menu-thumbs/menu-hd-onglet34/jus-mangue-224.webp', '/menu-thumbs/menu-hd-onglet34/jus-mangue-336.webp', 207, true),
  ('cb223847c5', 'jus', 'Jus Kiwi', 'Kiwi', '32.00', 'MAD', '/menu-hd-onglet34/jus-kiwi.png', '/menu-thumbs/menu-hd-onglet34/jus-kiwi-224.webp', '/menu-thumbs/menu-hd-onglet34/jus-kiwi-336.webp', 208, true),
  ('0229f0431e', 'boissons', 'Coca Cola', '33 cl', '15.00', 'MAD', '/menu-hd-onglet35/boisson-coca-cola.png', '/menu-thumbs/menu-hd-onglet35/boisson-coca-cola-224.webp', '/menu-thumbs/menu-hd-onglet35/boisson-coca-cola-336.webp', 209, true),
  ('8e12069c86', 'boissons', 'Coca Cola Zéro', '33 cl', '15.00', 'MAD', '/menu-hd-onglet35/boisson-coca-cola-zero.png', '/menu-thumbs/menu-hd-onglet35/boisson-coca-cola-zero-224.webp', '/menu-thumbs/menu-hd-onglet35/boisson-coca-cola-zero-336.webp', 210, true),
  ('4750e9d01c', 'boissons', 'Sprite', '33 cl', '15.00', 'MAD', '/menu-hd-onglet35/boisson-sprite.png', '/menu-thumbs/menu-hd-onglet35/boisson-sprite-224.webp', '/menu-thumbs/menu-hd-onglet35/boisson-sprite-336.webp', 211, true),
  ('cf01bd2066', 'boissons', 'Hawai', '33 cl', '15.00', 'MAD', '/menu-hd-onglet35/boisson-hawai.png', '/menu-thumbs/menu-hd-onglet35/boisson-hawai-224.webp', '/menu-thumbs/menu-hd-onglet35/boisson-hawai-336.webp', 212, true),
  ('5b62bf8e93', 'boissons', 'Poms', '33 cl', '15.00', 'MAD', '/menu-hd-onglet35/boisson-poms.png', '/menu-thumbs/menu-hd-onglet35/boisson-poms-224.webp', '/menu-thumbs/menu-hd-onglet35/boisson-poms-336.webp', 213, true)
on conflict (id) do update set
  category_id = excluded.category_id,
  name = excluded.name,
  description = excluded.description,
  price = excluded.price,
  currency = excluded.currency,
  image_url = excluded.image_url,
  thumb_small_url = excluded.thumb_small_url,
  thumb_large_url = excluded.thumb_large_url,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active;

insert into public.product_variants (product_id, id, label, price, sort_order, is_active) values
  ('8f3c2a91b0', 'fromage', 'Fromage', '39.00', 0, true),
  ('8f3c2a91b0', 'poulet', 'Poulet', '39.00', 1, true),
  ('8f3c2a91b0', 'saumon', 'Saumon', '49.00', 2, true),
  ('a1aee64eaf', 'poulet', 'Poulet', '44.00', 0, true),
  ('a1aee64eaf', 'crevettes', 'Crevettes', '54.00', 1, true),
  ('a720b7b300', 'poulet', 'Poulet', '39.00', 0, true),
  ('a720b7b300', 'crevettes', 'Crevettes', '49.00', 1, true),
  ('a720b7b300', 'mixte', 'Mixte', '49.00', 2, true),
  ('1842edff6e', 'gambas', 'Gambas', '78.00', 0, true),
  ('1842edff6e', 'saumon-crabe', 'Saumon Crabe', '78.00', 1, true),
  ('1842edff6e', 'chicken', 'Chicken', '74.00', 2, true),
  ('79bda10a6e', 'saumon-avocat', 'Saumon Avocat', '79.00', 0, true),
  ('79bda10a6e', 'crevettes-avocat', 'Crevettes Avocat', '74.00', 1, true),
  ('5a7a6c1ff9', 'saumon-avocat', 'Saumon Avocat', '79.00', 0, true),
  ('5a7a6c1ff9', 'crevettes-avocat', 'Crevettes Avocat', '74.00', 1, true),
  ('5a7a6c1ff9', 'chicken-fry-avocat', 'Chicken Fry Avocat', '69.00', 2, true),
  ('76d7875ff7', 'vegetarien', 'Végétarien', '29.00', 0, true),
  ('76d7875ff7', 'poulet', 'Poulet', '39.00', 1, true),
  ('76d7875ff7', 'crevettes', 'Crevettes', '44.00', 2, true),
  ('da996bc4a5', 'poulet', 'Poulet', '44.00', 0, true),
  ('da996bc4a5', 'crevettes', 'Crevettes', '54.00', 1, true),
  ('083ac320dd', 'vegetarien', 'Végétarien', '49.00', 0, true),
  ('083ac320dd', 'poulet', 'Poulet', '59.00', 1, true),
  ('083ac320dd', 'boeuf', 'Bœuf', '64.00', 2, true),
  ('083ac320dd', 'crevettes', 'Crevettes', '64.00', 3, true),
  ('083ac320dd', 'fruits-de-mer', 'Fruits de mer', '74.00', 4, true),
  ('0c48c8093e', 'vegetarien', 'Végétarien', '49.00', 0, true),
  ('0c48c8093e', 'poulet', 'Poulet', '59.00', 1, true),
  ('0c48c8093e', 'boeuf', 'Bœuf', '64.00', 2, true),
  ('0c48c8093e', 'crevettes', 'Crevettes', '64.00', 3, true),
  ('0c48c8093e', 'fruits-de-mer', 'Fruits de mer', '74.00', 4, true),
  ('5c227884f6', 'vegetarien', 'Végétarien', '44.00', 0, true),
  ('5c227884f6', 'poulet', 'Poulet', '54.00', 1, true),
  ('5c227884f6', 'boeuf', 'Bœuf', '59.00', 2, true),
  ('5c227884f6', 'crevettes', 'Crevettes', '64.00', 3, true),
  ('5c227884f6', 'fruits-de-mer', 'Fruits de mer', '69.00', 4, true),
  ('382bef2bb1', 'poulet', 'Poulet', '64.00', 0, true),
  ('382bef2bb1', 'boeuf', 'Bœuf', '74.00', 1, true),
  ('382bef2bb1', 'crevettes', 'Crevettes', '74.00', 2, true),
  ('382bef2bb1', 'fruits-de-mer', 'Fruits de Mer', '79.00', 3, true),
  ('36987b1e67', 'poulet', 'Poulet', '69.00', 0, true),
  ('36987b1e67', 'boeuf', 'Bœuf', '74.00', 1, true),
  ('36987b1e67', 'crevette', 'Crevette', '74.00', 2, true),
  ('36987b1e67', 'fruits-de-mer', 'Fruits de mer', '79.00', 3, true),
  ('9eba998f82', 'poulet', 'Poulet', '69.00', 0, true),
  ('9eba998f82', 'boeuf', 'Bœuf', '74.00', 1, true),
  ('9eba998f82', 'crevette', 'Crevette', '74.00', 2, true),
  ('9eba998f82', 'fruits-de-mer', 'Fruits de mer', '79.00', 3, true),
  ('9443eb67b5', 'poulet', 'Poulet', '69.00', 0, true),
  ('9443eb67b5', 'boeuf', 'Bœuf', '74.00', 1, true),
  ('9443eb67b5', 'crevette', 'Crevette', '74.00', 2, true),
  ('9443eb67b5', 'fruits-de-mer', 'Fruits de mer', '79.00', 3, true),
  ('a8016335cd', 'poulet', 'Poulet', '69.00', 0, true),
  ('a8016335cd', 'boeuf', 'Bœuf', '74.00', 1, true),
  ('a8016335cd', 'crevette', 'Crevette', '74.00', 2, true),
  ('a8016335cd', 'fruits-de-mer', 'Fruits de mer', '79.00', 3, true),
  ('4afcd30489', 'poulet', 'Poulet', '69.00', 0, true),
  ('4afcd30489', 'boeuf', 'Bœuf', '74.00', 1, true),
  ('4afcd30489', 'crevette', 'Crevette', '74.00', 2, true),
  ('4afcd30489', 'fruits-de-mer', 'Fruits de mer', '79.00', 3, true),
  ('9e1d2c99ca', 'poulet', 'Poulet', '69.00', 0, true),
  ('9e1d2c99ca', 'boeuf', 'Bœuf', '74.00', 1, true),
  ('9e1d2c99ca', 'crevette', 'Crevette', '74.00', 2, true),
  ('9e1d2c99ca', 'fruits-de-mer', 'Fruits de mer', '79.00', 3, true),
  ('1568a2e365', 'poulet', 'Poulet', '69.00', 0, true),
  ('1568a2e365', 'boeuf', 'Bœuf', '84.00', 1, true),
  ('1568a2e365', 'saumon', 'Saumon', '89.00', 2, true)
on conflict (product_id, id) do update set
  label = excluded.label,
  price = excluded.price,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active;

commit;
